x-airflow-env: &airflow-env
  RUN_ENV: docker
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_AIRFLOW_USER}:${POSTGRES_AIRFLOW_PASSWORD}@airflow_postgres:5432/${POSTGRES_AIRFLOW_DB}
  _AIRFLOW_WWW_USER_CREATE: "true"
  _AIRFLOW_WWW_USER_USERNAME: airflow
  _AIRFLOW_WWW_USER_PASSWORD: airflow
  PYTHONPATH: "/opt/airflow/"
  DBT_PROFILES_DIR: /opt/dbt
  GOOGLE_APPLICATION_CREDENTIALS: /opt/gcp/adc.json
  #GOOGLE_APPLICATION_CREDENTIALS: /opt/gcp/service-account.json

x-airflow-common: 
  &airflow-common
  build:
    context: ./docker/airflow
    dockerfile: Dockerfile
  env_file:
    - .env
  environment:
    <<: *airflow-env
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./airflow/config:/opt/airflow/config
    - ./finpro_dbt:/opt/dbt
    - ./src:/opt/airflow/src
    - ~/.config/gcloud/application_default_credentials.json:/opt/gcp/adc.json:ro
    # - ./gcp:/opt/gcp
  networks:
    - project-net
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    airflow_postgres:
      condition: service_healthy

services:
  airflow_postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_AIRFLOW_USER}
      POSTGRES_PASSWORD: ${POSTGRES_AIRFLOW_PASSWORD}
      POSTGRES_DB: ${POSTGRES_AIRFLOW_DB}
    ports:
      - "${POSTGRES_AIRFLOW_PORT}:5432"
    volumes:
      - pg_airflow_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_AIRFLOW_USER}"]
      interval: 5s
      retries: 5
    networks:
      - project-net

  dwh_postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_DWH_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DWH_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DWH_DB}
    ports:
      - "${POSTGRES_DWH_PORT_EXT}:5432"
    volumes:
      - pg_dwh_data:/var/lib/postgresql/data
      - ./docker/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_DWH_USER}"]
      interval: 5s
      retries: 5
    networks:
      - project-net

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow db migrate
    environment:
      <<: *airflow-env
      _AIRFLOW_DB_MIGRATE: 'true'
    user: "0:0"
    volumes:
      - ./airflow:/sources

  airflow-webserver:
    <<: *airflow-common
    environment:
      <<: *airflow-env
    command: webserver
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    environment:
      <<: *airflow-env
    command: scheduler
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
      interval: 10s
      timeout: 10s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    volumes:
      - zk_data:/var/lib/zookeeper/data
      - zk_log:/var/lib/zookeeper/log
    networks:
      - project-net
    healthcheck:
      test: ["CMD", "bash", "-c", "echo stat | nc 127.0.0.1 2181"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:${KAFKA_PORT},PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:${KAFKA_PORT},PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "${KAFKA_PORT}:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - project-net
    healthcheck:
      test: ["CMD", "bash", "-c", "kafka-broker-api-versions --bootstrap-server kafka:29092 >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "${KAFKA_UI_PORT}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:${ZOOKEEPER_PORT}
    depends_on:
      - kafka
    networks:
      - project-net

  loader:
    build:
      context: .
      dockerfile: docker/loader/Dockerfile
    env_file:
      - .env
    environment:
      RUN_ENV: docker
      KAFKA_BROKER: kafka:29092
      POSTGRES_HOST: ${POSTGRES_DWH_HOST}
      POSTGRES_PORT: ${POSTGRES_DWH_PORT}
      POSTGRES_DB: ${POSTGRES_DWH_DB}
      POSTGRES_USER: ${POSTGRES_DWH_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DWH_PASSWORD}
      LOADER_BATCH_SIZE: 100
      LOADER_FLUSH_INTERVAL: 5
    depends_on:
      kafka:
        condition: service_healthy
      dwh_postgres:
        condition: service_started
    restart: always
    networks:
      - project-net

networks:
  project-net:

volumes:
  pg_airflow_data:
  pg_dwh_data:
  zk_data:
  zk_log:
  kafka_data: